### ISSUE TITLE
ckb_dlopen2 error when number of entries in .rela.dyn section exceeds 64

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/ckb-c-stdlib#37]
The code https://github.com/nervosnetwork/ckb-c-stdlib/blob/20578dfb092b3b3761df755395e20ec142a83d6e/ckb_dlfcn.h#L339-L374 processes section `SHT_RELA` by loading a batch of 64 entries into `Elf64_Rela relocations[64]`. When we can not finish loading in one try, we decrease the entry counter and increase the loading offset in https://github.com/nervosnetwork/ckb-c-stdlib/blob/20578dfb092b3b3761df755395e20ec142a83d6e/ckb_dlfcn.h#L357-L358. The problem is that the variable `load_length`, which is supposed to be the length of the data we have loaded, is been overwritten by the syscall `ckb_load_cell_data` in https://github.com/nervosnetwork/ckb-c-stdlib/blob/20578dfb092b3b3761df755395e20ec142a83d6e/ckb_dlfcn.h#L349-L350. 

Here are the result when I print parameters after  https://github.com/nervosnetwork/ckb-c-stdlib/blob/20578dfb092b3b3761df755395e20ec142a83d6e/ckb_dlfcn.h#L348
```
DEBUG:<unknown>: SCRIPT>ckb_dlopen2 working on relocations relocation_size 556, load_size 64, load_length 1536, current_offset 12080, rela_size 24
```
and result before https://github.com/nervosnetwork/ckb-c-stdlib/blob/20578dfb092b3b3761df755395e20ec142a83d6e/ckb_dlfcn.h#L354
```
DEBUG:<unknown>: SCRIPT>ckb_dlopen2 loaded cell data relocation_size 556, load_size 64, load_length 251248
```
It is obvious that load_length has been changed from 1536 to 251248.

We should use `current_offset += load_size * sizeof(Elf64_Rela);` instead.

This problem will only become apparent if the number of entries exceeds 64 (the batch size).

**Comment by XuJiandong** [comment]
considering if length is smaller than `load_size * sizeof(Elf64_Rela)`.
